import { Inter } from 'next/font/google';
import './globals.css';
import BodyContainer from '@/src/layout/bodyContainer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={`${inter.className}`}>
        <BodyContainer>{children}</BodyContainer>
      </body>
    </html>
  );
}
